import { useEffect, useState } from "react";
import { Link, createFileRoute, useNavigate } from "@tanstack/react-router";
import { Plus, FolderKanban, MoreHorizontal, Archive, Trash2, LogOut, Shield } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Logo } from "@/components/brand/logo";
import { requireUser } from "@/lib/auth";

export const Route = createFileRoute("/dashboard")({ component: DashboardPage });

type Project = { id:string; name:string; description:string; status:"active"|"archived"; file_count:number; folder_count:number; storage_bytes:number; current_version:number; updated_at:string; created_at:string };

function DashboardPage(){const navigate=useNavigate();const[projects,setProjects]=useState<Project[]>([]);const[name,setName]=useState("");const[description,setDescription]=useState("");const[showCreate,setShowCreate]=useState(false);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  async function load(){setLoading(true);const user=await requireUser();const{data,error}=await supabase.from("projects").select("*").eq("owner_id",user.id).order("updated_at",{ascending:false});if(error)setError(error.message);setProjects((data??[]) as Project[]);setLoading(false)}
  useEffect(()=>{load().catch(()=>navigate({to:"/login"}))},[]);
  async function createProject(e:React.FormEvent){e.preventDefault();const user=await requireUser();if(!name.trim())return;const{data,error}=await supabase.from("projects").insert({owner_id:user.id,name:name.trim(),description:description.trim()}).select().single();if(error)setError(error.message);else{setName("");setDescription("");setShowCreate(false);if(data)await navigate({to:"/projects/$id",params:{id:data.id}})} }
  async function archive(id:string){await supabase.from("projects").update({status:"archived"}).eq("id",id);load()}
  async function remove(id:string){if(!confirm("Delete this project permanently?"))return;await supabase.from("projects").delete().eq("id",id);load()}
  async function signOut(){await supabase.auth.signOut();await navigate({to:"/"})}
  return <main className="min-h-screen bg-[#080b0a] text-[#f4f3ee]"><header className="border-b border-white/8"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10"><Logo showWordmark/><div className="flex items-center gap-2"><Link to="/admin" className="rounded-full border border-white/8 p-2.5 text-white/45 hover:text-white" title="Admin"><Shield className="h-4 w-4"/></Link><button onClick={signOut} className="rounded-full border border-white/8 p-2.5 text-white/45 hover:text-white" title="Sign out"><LogOut className="h-4 w-4"/></button></div></div></header><div className="mx-auto max-w-7xl px-6 py-12 lg:px-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-[.2em] text-[#d7e5b0]/60">Your vault</p><h1 className="mt-2 text-4xl tracking-[-.04em]">Projects</h1><p className="mt-2 text-sm text-white/40">Real projects backed by your private filesystem.</p></div><button onClick={()=>setShowCreate(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#d7e5b0] px-5 py-3 text-sm font-semibold text-[#10150f]"><Plus className="h-4 w-4"/> New project</button></div>{error&&<p className="mt-6 rounded-xl border border-red-400/20 bg-red-400/5 px-4 py-3 text-sm text-red-200">{error}</p>}{showCreate&&<form onSubmit={createProject} className="mt-8 rounded-2xl border border-white/10 bg-white/[.025] p-6"><div className="grid gap-4 md:grid-cols-[1fr_1fr_auto]"><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Project name" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm outline-none focus:border-[#d7e5b0]/50"/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description (optional)" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm outline-none focus:border-[#d7e5b0]/50"/><button className="rounded-xl bg-white/10 px-5 py-3 text-sm hover:bg-white/15">Create</button></div></form>}
  {loading?<div className="py-24 text-center text-sm text-white/35">Loading your projects…</div>:projects.length===0?<div className="mt-10 rounded-3xl border border-dashed border-white/10 p-16 text-center"><FolderKanban className="mx-auto h-8 w-8 text-white/20"/><h2 className="mt-5 text-xl">Your vault is empty</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-white/35">Create a project to open a real code workspace. Nothing is stored only in the browser.</p></div>:<div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{projects.map(p=><article key={p.id} className="group rounded-3xl border border-white/8 bg-white/[.025] p-6 transition hover:-translate-y-0.5 hover:border-white/15"><div className="flex items-start justify-between"><Link to="/projects/$id" params={{id:p.id}} className="min-w-0"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#d7e5b0]/10 text-[#d7e5b0]"><FolderKanban className="h-5 w-5"/></div><h2 className="mt-5 truncate text-lg font-medium">{p.name}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-white/35">{p.description||"No description"}</p></Link><div className="relative"><button onClick={()=>{const a=prompt("Type ARCHIVE to archive or DELETE to delete");if(a==="ARCHIVE")archive(p.id);if(a==="DELETE")remove(p.id)}} className="rounded-lg p-2 text-white/25 hover:bg-white/5 hover:text-white"><MoreHorizontal className="h-4 w-4"/></button></div></div><div className="mt-7 flex gap-5 border-t border-white/6 pt-4 text-xs text-white/30"><span>{p.file_count} files</span><span>v{p.current_version}</span><span>{new Date(p.updated_at).toLocaleDateString()}</span></div>{p.status==="archived"&&<div className="mt-3 inline-flex items-center gap-1 text-[11px] text-amber-200/60"><Archive className="h-3 w-3"/> Archived</div>}<button onClick={()=>remove(p.id)} className="mt-5 hidden items-center gap-1 text-xs text-red-300/60 hover:text-red-200 group-hover:flex"><Trash2 className="h-3 w-3"/> Delete</button></article>)}</div>}</div></main>}
