import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Boxes, GitBranch, LockKeyhole, Sparkles, TerminalSquare, Waypoints } from "lucide-react";
import { AetherLogo, AetherMark } from "@/components/brand/logo";

export const Route = createFileRoute("/")({ component: Index });

function Index() {
  return <div className="min-h-screen overflow-hidden bg-background">
    <header className="sticky top-0 z-20 border-b border-border/70 bg-background/85 backdrop-blur-xl">
      <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><AetherLogo /><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#workspace" className="hover:text-foreground">Workspace</a><a href="#security" className="hover:text-foreground">Security</a><a href="#mcp" className="hover:text-foreground">MCP</a></nav><div className="flex items-center gap-2"><Link to="/login" className="hidden px-3 py-2 text-sm text-muted-foreground hover:text-foreground sm:block">Sign in</Link><Link to="/signup" className="vault-button-primary">Open your vault <ArrowRight className="size-4" /></Link></div></div>
    </header>
    <main>
      <section className="vault-grid vault-aura relative isolate"><div className="mx-auto max-w-7xl px-5 pb-24 pt-24 lg:px-8 lg:pb-32 lg:pt-32"><div className="max-w-4xl animate-rise"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-border bg-surface/80 px-3 py-1.5 font-mono text-[10px] tracking-[0.22em] text-primary uppercase"><span className="size-1.5 rounded-full bg-primary animate-beacon" /> Private by default</div><h1 className="max-w-4xl text-5xl font-semibold leading-[1.02] tracking-[-0.045em] sm:text-6xl lg:text-8xl">Your code,<br /><span className="text-gradient-aether">sealed in Aether.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">A private cloud workspace for source code, versioned project history, and carefully authorized AI access. Built for ownership first.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/signup" className="vault-button-primary h-12 px-5">Create your vault <ArrowRight className="size-4" /></Link><Link to="/login" className="vault-button-secondary h-12 px-5">Sign in</Link></div></div><div className="mt-20 grid max-w-5xl grid-cols-1 gap-3 sm:grid-cols-3"><Stat icon={<LockKeyhole />} title="Private storage" text="Project content lives behind access control." /><Stat icon={<GitBranch />} title="Versioned" text="Snapshots preserve the history of your work." /><Stat icon={<Waypoints />} title="AI-ready" text="MCP access is scoped, audited and revocable." /></div></div></section>
      <section id="workspace" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><Eyebrow>THE WORKSPACE</Eyebrow><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">A real code workspace.<br />Nothing simulated.</h2><p className="mt-5 max-w-lg leading-7 text-muted-foreground">Browse projects, open real files, edit code, save changes and search your project without leaving the vault.</p><div className="mt-7 space-y-3 text-sm text-muted-foreground"><Feature icon={<TerminalSquare />} text="Monaco-powered editing" /><Feature icon={<Boxes />} text="Nested files and folders" /><Feature icon={<Sparkles />} text="Aether-native interaction design" /></div></div><WorkspacePreview /></div></section>
      <section id="security" className="border-y border-border bg-surface-sunken"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="max-w-2xl"><Eyebrow>THE VAULT</Eyebrow><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Security is part of the architecture.</h2><p className="mt-5 leading-7 text-muted-foreground">Authorization is enforced server-side and reinforced by database isolation. Sensitive filenames, unsafe paths and oversized content are handled by the vault's security layer.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3"><SecurityCard title="Project isolation" text="Users can only operate on projects they are authorized to access." /><SecurityCard title="Private content" text="File bytes live in private object storage rather than public URLs." /><SecurityCard title="Audited actions" text="Important project and AI operations leave an accountable activity trail." /></div></div></section>
      <section id="mcp" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="panel-raised overflow-hidden"><div className="grid lg:grid-cols-[1fr_0.9fr]"><div className="p-8 sm:p-12"><Eyebrow>MCP / AI ACCESS</Eyebrow><h2 className="mt-4 text-4xl font-semibold tracking-tight">Give AI a key, not the whole building.</h2><p className="mt-5 max-w-xl leading-7 text-muted-foreground">Aether Code Vault is designed to expose selected project capabilities through a real MCP server. Clients receive explicit permissions and project scope, not unrestricted filesystem access.</p><div className="mt-8 flex items-center gap-3 font-mono text-xs text-primary"><span className="size-2 rounded-full bg-primary" /> AUTHENTICATED · SCOPED · AUDITED</div></div><div className="border-t border-border bg-editor p-8 font-mono text-xs leading-7 text-muted-foreground lg:border-l lg:border-t-0"><div className="text-primary">MCP / project.read</div><div className="mt-3">→ list_files</div><div>→ read_file</div><div>→ search_code</div><div className="mt-4 text-brass">future / guarded writes</div><div>→ create_file</div><div>→ update_file</div><div>→ create_snapshot</div></div></div></div></section>
      <section className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="vault-grid panel p-10 text-center sm:p-16"><AetherMark className="mx-auto size-12" /><h2 className="mt-6 text-3xl font-semibold sm:text-4xl">Build privately. Connect deliberately.</h2><p className="mx-auto mt-4 max-w-xl text-muted-foreground">Aether Code Vault is the secure foundation for the developer tools and authorized AI workflows you will build on top of it.</p><Link to="/signup" className="vault-button-primary mx-auto mt-8">Create your vault <ArrowRight className="size-4" /></Link></div></section>
    </main>
    <footer className="border-t border-border"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-8"><AetherLogo size="sm" /><span>Private code infrastructure, designed for Aether.</span></div></footer>
  </div>;
}

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="font-mono text-[10px] tracking-[0.28em] text-primary uppercase">{children}</p>; }
function Stat({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="panel p-5"><div className="mb-4 text-primary">{icon}</div><p className="font-medium">{title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
function Feature({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="flex items-center gap-3"><span className="text-primary">{icon}</span>{text}</div>; }
function SecurityCard({ title, text }: { title: string; text: string }) { return <div className="panel p-6"><LockKeyhole className="size-5 text-primary" /><h3 className="mt-5 font-medium">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
function WorkspacePreview() { return <div className="panel-raised overflow-hidden shadow-panel"><div className="flex items-center gap-2 border-b border-border bg-surface-raised px-4 py-3"><AetherMark className="size-4" quiet /><span className="font-mono text-[10px] text-muted-foreground">aether / workspace</span><span className="ml-auto size-2 rounded-full bg-success" /></div><div className="grid min-h-[360px] grid-cols-[150px_1fr]"><aside className="border-r border-border bg-surface-sunken p-3 font-mono text-[10px] text-muted-foreground"><div className="text-foreground">▾ src</div><div className="mt-2 pl-3">▾ components</div><div className="pl-6 text-primary">App.tsx</div><div className="pl-6">logo.tsx</div><div className="mt-2 pl-3">routes</div><div className="mt-3">package.json</div></aside><div className="bg-editor p-5 font-mono text-xs leading-7 text-muted-foreground"><div><span className="text-brass">export</span> <span className="text-primary">default</span> <span className="text-foreground">function</span> <span className="text-foreground">AetherWorkspace</span>() {'{'}</div><div className="pl-5">return <span className="text-primary">&lt;Vault /&gt;</span></div><div>{'}'}</div><div className="mt-7 h-px bg-border" /><div className="mt-4 text-[10px] text-muted-foreground/60">All changes persist to the private project filesystem.</div></div></div></div>; }
