import { useEffect, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Activity, Database, FolderKanban, LogOut, ShieldCheck, Users, HardDrive, KeyRound } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { getRole } from "@/lib/auth";

export const Route=createFileRoute("/admin/")({component:AdminDashboard});
function AdminDashboard(){const navigate=useNavigate();const[stats,setStats]=useState({users:0,projects:0,storage:0,audit:0,mcp:0});const[events,setEvents]=useState<any[]>([]);const[error,setError]=useState("");
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){await navigate({to:"/admin/login"});return}const role=await getRole(user.id);if(role!=="admin"&&role!=="platform_owner"){await supabase.auth.signOut();await navigate({to:"/admin/login"});return}const [users,projects,storage,audit,mcp]=await Promise.all([supabase.from("profiles").select("id",{count:"exact",head:true}),supabase.from("projects").select("id",{count:"exact",head:true}),supabase.from("projects").select("storage_bytes"),supabase.from("audit_events").select("id,action,actor_type,success,created_at").order("created_at",{ascending:false}).limit(12),supabase.from("mcp_clients").select("id",{count:"exact",head:true})]);setStats({users:users.count??0,projects:projects.count??0,storage:(storage.data??[]).reduce((s:any,p:any)=>s+Number(p.storage_bytes||0),0),audit:audit.data?.length??0,mcp:mcp.count??0});setEvents(audit.data??[]);})().catch(e=>setError(e.message))},[]);
 async function logout(){await supabase.auth.signOut();await navigate({to:"/admin/login"})}
 const cards=[[Users,"Users",stats.users],[FolderKanban,"Projects",stats.projects],[HardDrive,"Stored bytes",formatBytes(stats.storage)],[KeyRound,"MCP clients",stats.mcp]] as const;
 return <main className="min-h-screen bg-[#070907] text-[#f4f3ee]"><header className="border-b border-white/8"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10"><div><div className="text-[10px] uppercase tracking-[.25em] text-[#d7e5b0]/60">Aether Code Vault</div><div className="mt-1 text-sm">Platform control plane</div></div><div className="flex items-center gap-3"><Link to="/dashboard" className="text-xs text-white/35 hover:text-white">User app</Link><button onClick={logout} className="rounded-lg border border-white/8 p-2 text-white/40 hover:text-white"><LogOut className="h-4 w-4"/></button></div></div></header><div className="mx-auto max-w-7xl px-6 py-10 lg:px-10"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([Icon,label,value])=><article key={label} className="rounded-2xl border border-white/8 bg-white/[.025] p-5"><Icon className="h-4 w-4 text-[#d7e5b0]"/><div className="mt-7 text-xs uppercase tracking-[.15em] text-white/25">{label}</div><div className="mt-2 text-2xl">{value}</div></article>)}</div><div className="mt-8 grid gap-5 lg:grid-cols-[1.4fr_.8fr]"><section className="rounded-2xl border border-white/8 bg-white/[.025] p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg">Recent activity</h2><p className="mt-1 text-xs text-white/30">Latest platform events visible to administrators.</p></div><Activity className="h-4 w-4 text-white/25"/></div>{error&&<p className="mt-5 text-sm text-red-200">{error}</p>}<div className="mt-6 space-y-2">{events.map(e=><div key={e.id} className="flex items-center justify-between rounded-xl border border-white/5 px-4 py-3"><div className="min-w-0"><div className="truncate text-sm text-white/65">{e.action}</div><div className="mt-1 text-[11px] text-white/25">{e.actor_type} · {new Date(e.created_at).toLocaleString()}</div></div><span className={e.success?"text-[#d7e5b0]/60":"text-red-200/70"}>{e.success?"OK":"Failed"}</span></div>)}{events.length===0&&<div className="py-12 text-center text-sm text-white/25">No recent events.</div>}</div></section><aside className="space-y-4"><AdminLink icon={ShieldCheck} title="Security" text="Review platform security state and sensitive-file policy."/><AdminLink icon={Database} title="Projects & storage" text="Inspect real project and storage metadata."/><AdminLink icon={KeyRound} title="MCP control" text="Manage authorized AI clients and permissions."/></aside></div></div></main>}
function AdminLink({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-5"><Icon className="h-4 w-4 text-[#d7e5b0]"/><h3 className="mt-6 text-sm">{title}</h3><p className="mt-2 text-xs leading-5 text-white/30">{text}</p></div>}
function formatBytes(n:number){if(!n)return"0 B";const u=["B","KB","MB","GB","TB"];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),u.length-1);return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`}
