import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Copy, KeyRound, Plus, ShieldCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { getRole } from "@/lib/auth";

export const Route=createFileRoute("/admin/mcp")({component:McpAdmin});
type Project={id:string;name:string};type Client={id:string;name:string;token_prefix:string;scopes:string[];project_ids:string[];expires_at:string|null;revoked_at:string|null;created_at:string};
async function sha256(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function McpAdmin(){const[projects,setProjects]=useState<Project[]>([]);const[clients,setClients]=useState<Client[]>([]);const[name,setName]=useState("");const[scope,setScope]=useState("project.read");const[selected,setSelected]=useState<string[]>([]);const[issued,setIssued]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user||!['admin','platform_owner'].includes(await getRole(user.id)))throw new Error("Administrator access required");const[p,c]=await Promise.all([supabase.from("projects").select("id,name").order("name"),supabase.from("mcp_clients").select("*").order("created_at",{ascending:false})]);if(p.error)throw p.error;if(c.error)throw c.error;setProjects((p.data??[]) as Project[]);setClients((c.data??[]) as Client[])}useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function create(){setBusy(true);setError("");const{data:{user}}=await supabase.auth.getUser();if(!user){setError("Not authenticated");setBusy(false);return}if(!name.trim()||selected.length===0){setError("Give the client a name and select at least one project.");setBusy(false);return}const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);const raw=`acv_${Array.from(bytes).map(b=>b.toString(16).padStart(2,"0")).join("")}`;const hash=await sha256(raw);const{error}=await supabase.from("mcp_clients").insert({owner_id:user.id,name:name.trim(),description:"Aether Code Vault MCP client",token_prefix:raw.slice(0,12),token_hash:hash,scopes:[scope],project_ids:selected});if(error)setError(error.message);else{setIssued(raw);setName("");setSelected([]);await load()}setBusy(false)}
 async function revoke(id:string){if(!confirm("Revoke this MCP credential? It cannot be used again."))return;await supabase.from("mcp_clients").update({revoked_at:new Date().toISOString()}).eq("id",id);load()}
 return <main className="min-h-screen bg-[#070907] text-[#f4f3ee]"><div className="mx-auto max-w-6xl px-6 py-10 lg:px-10"><Link to="/admin" className="inline-flex items-center gap-2 text-sm text-white/35 hover:text-white"><ArrowLeft className="h-4 w-4"/> Control plane</Link><div className="mt-10"><p className="text-xs uppercase tracking-[.2em] text-[#d7e5b0]/60">AI access</p><h1 className="mt-2 text-4xl tracking-[-.04em]">MCP clients</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/40">Issue project-scoped bearer credentials for authorized AI clients. Tokens are shown once and stored only as hashes.</p></div>{issued&&<div className="mt-8 rounded-2xl border border-[#d7e5b0]/20 bg-[#d7e5b0]/5 p-5"><div className="text-xs uppercase tracking-[.16em] text-[#d7e5b0]/70">Copy this token now</div><p className="mt-2 text-xs text-white/35">It will not be displayed again.</p><div className="mt-4 flex gap-2"><code className="min-w-0 flex-1 overflow-auto rounded-lg bg-black/20 px-3 py-2 text-xs text-[#d7e5b0]">{issued}</code><button onClick={()=>navigator.clipboard.writeText(issued)} className="rounded-lg border border-white/10 p-2"><Copy className="h-4 w-4"/></button></div></div>}
 <div className="mt-8 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><section className="rounded-2xl border border-white/8 bg-white/[.025] p-6"><div className="flex items-center gap-3"><KeyRound className="h-4 w-4 text-[#d7e5b0]"/><h2>Issue credential</h2></div><div className="mt-6 space-y-4"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Client name" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm outline-none focus:border-[#d7e5b0]/50"/><select value={scope} onChange={e=>setScope(e.target.value)} className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm"><option value="project.read">project.read</option><option value="project.search">project.search</option><option value="file.read">file.read</option></select><div><div className="mb-2 text-xs uppercase tracking-[.12em] text-white/35">Authorized projects</div><div className="max-h-48 space-y-2 overflow-auto">{projects.map(p=><label key={p.id} className="flex items-center gap-3 rounded-lg border border-white/6 px-3 py-2 text-xs text-white/60"><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,p.id]:s.filter(x=>x!==p.id))}/>{p.name}</label>)}</div></div><button disabled={busy} onClick={create} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#d7e5b0] px-4 py-3 text-sm font-semibold text-[#10150f]"><Plus className="h-4 w-4"/>{busy?"Issuing…":"Issue MCP credential"}</button></div>{error&&<p className="mt-4 text-sm text-red-200">{error}</p>}</section><section className="rounded-2xl border border-white/8 bg-white/[.025] p-6"><div className="flex items-center gap-3"><ShieldCheck className="h-4 w-4 text-[#d7e5b0]"/><h2>Issued clients</h2></div><div className="mt-6 space-y-2">{clients.map(c=><div key={c.id} className="rounded-xl border border-white/6 p-4"><div className="flex items-center justify-between gap-3"><div><div className="text-sm">{c.name}</div><div className="mt-1 font-mono text-[11px] text-white/25">{c.token_prefix}… · {c.scopes.join(", ")}</div></div>{c.revoked_at?<span className="text-xs text-red-200/60">Revoked</span>:<button onClick={()=>revoke(c.id)} className="text-xs text-white/35 hover:text-red-200">Revoke</button>}</div></div>)}{clients.length===0&&<p className="py-10 text-center text-sm text-white/25">No MCP clients yet.</p>}</div></section></div></div></main>}
