import { unzipSync, zipSync, strToU8, u8ToStr } from "fflate";
import { Download, Upload } from "lucide-react";
import { useRef, useState } from "react";
import { createProjectFolder, getProjectFile, getProjectNodes, importProjectArchive } from "@/lib/vault.functions";
import type { VaultNode } from "@/lib/server/files.server";

const MAX_ARCHIVE_BYTES = 25 * 1024 * 1024;
const MAX_EXTRACTED_BYTES = 50 * 1024 * 1024;
const MAX_ENTRIES = 2000;
function safePath(path:string){return !path.startsWith("/")&&!path.includes("\\")&&!path.split("/").some(s=>s===".."||s==="."||!s);}
export function ArchiveActions({projectId}:{projectId:string}){const input=useRef<HTMLInputElement>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
async function exportZip(){setBusy(true);setError("");try{const nodes=await getProjectNodes({data:{projectId}});if(nodes.length>MAX_ENTRIES)throw new Error("This project exceeds the archive entry limit.");const files:Record<string,Uint8Array>={};for(const node of nodes.filter(n=>n.type==="file")){const result=await getProjectFile({data:{projectId,path:node.path}});if(result.encoding==="base64"){const binary=atob(result.content);files[node.path]=Uint8Array.from(binary,c=>c.charCodeAt(0));}else files[node.path]=strToU8(result.content);}const archive=zipSync(files,{level:6});const blob=new Blob([archive],{type:"application/zip"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="aether-code-vault.zip";a.click();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:"Export failed.");}finally{setBusy(false)}}
async function importZip(file:File){if(file.size>MAX_ARCHIVE_BYTES)throw new Error("ZIP is larger than the 25 MB upload limit.");const bytes=new Uint8Array(await file.arrayBuffer());const entries=unzipSync(bytes);const keys=Object.keys(entries);if(keys.length>MAX_ENTRIES)throw new Error("ZIP contains too many entries.");let total=0;const payload:{path:string;type:"file"|"folder";contentBase64?:string}[]=[];for(const raw of keys){const normalized=raw.replace(/\/+$/,"/").replace(/^\.\//,"");if(!safePath(normalized))throw new Error(`Unsafe archive path: ${raw}`);const data=entries[raw];if(raw.endsWith("/")){payload.push({path:normalized.replace(/\/$/,""),type:"folder"});continue;}total+=data.byteLength;if(total>MAX_EXTRACTED_BYTES)throw new Error("ZIP exceeds the 50 MB extracted-content limit.");let binary="";for(const b of data)binary+=String.fromCharCode(b);payload.push({path:normalized,type:"file",contentBase64:btoa(binary)});}if(!payload.length)throw new Error("ZIP contains no usable entries.");await importProjectArchive({data:{projectId,entries:payload}});}
async function choose(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;setBusy(true);setError("");try{await importZip(file);window.location.reload();}catch(err){setError(err instanceof Error?err.message:"Import failed.");}finally{setBusy(false)}}return <div className="flex items-center gap-1"><input ref={input} type="file" accept=".zip,application/zip" className="hidden" onChange={choose}/><button disabled={busy} onClick={()=>input.current?.click()} className="rounded-md p-2 text-muted-foreground hover:bg-surface-raised hover:text-foreground" title="Import ZIP"><Upload className="size-4"/></button><button disabled={busy} onClick={exportZip} className="rounded-md p-2 text-muted-foreground hover:bg-surface-raised hover:text-foreground" title="Export ZIP"><Download className="size-4"/></button>{error&&<span className="max-w-64 truncate text-xs text-destructive" title={error}>{error}</span>}</div>}
