import { useEffect, useState } from "react";
import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowLeft, GitCompareArrows, RotateCcw, Plus, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { requireUser } from "@/lib/auth";

export const Route = createFileRoute("/projects/$id/snapshots")({ component: SnapshotsPage });
type Snap={id:string;version:number;label:string;message:string;origin:string;file_count:number;folder_count:number;storage_bytes:number;created_at:string};
type Entry={path:string;type:string;content_hash:string|null;size_bytes:number};
function SnapshotsPage(){const{id}=Route.useParams();const[snaps,setSnaps]=useState<Snap[]>([]);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[compare,setCompare]=useState<{left:Snap;right:Snap}|null>(null);const[diff,setDiff]=useState<{added:string[];removed:string[];changed:string[]}>({added:[],removed:[],changed:[]});
 async function load(){await requireUser();const{data,error}=await supabase.from("snapshots").select("*").eq("project_id",id).order("version",{ascending:false});if(error)throw error;setSnaps((data??[]) as Snap[])}useEffect(()=>{load().catch(e=>setError(e.message))},[id]);
 async function createSnapshot(label?:string,origin="manual"){setBusy(true);setError("");const user=await requireUser();const{data:project}=await supabase.from("projects").select("current_version").eq("id",id).single();const{data:nodes,error:ne}=await supabase.from("project_nodes").select("*").eq("project_id",id);if(ne){setError(ne.message);setBusy(false);return null}const version=(project?.current_version??0)+1;const{data:snap,error}=await supabase.from("snapshots").insert({project_id:id,created_by:user.id,version,label:label??`Version ${version}`,message:origin==="restore"?"Restored project state":"Manual snapshot",origin,file_count:(nodes??[]).filter(n=>n.type==="file").length,folder_count:(nodes??[]).filter(n=>n.type==="folder").length,storage_bytes:(nodes??[]).reduce((s,n)=>s+Number(n.size_bytes||0),0)}).select().single();if(error||!snap){setError(error?.message||"Could not create snapshot");setBusy(false);return null}const entries=(nodes??[]).map(n=>({snapshot_id:snap.id,project_id:id,path:n.path,type:n.type,mime_type:n.mime_type,size_bytes:n.size_bytes,content_hash:n.content_hash,storage_key:n.storage_key,is_sensitive:n.is_sensitive}));if(entries.length){const{error}=await supabase.from("snapshot_entries").insert(entries);if(error)setError(error.message)}await supabase.from("projects").update({current_version:version}).eq("id",id);await load();setBusy(false);return snap as Snap}
 async function restore(s:Snap){if(!confirm(`Restore ${s.label}? The current filesystem will be replaced, then a new snapshot will record the restored state.`))return;setBusy(true);setError("");const{data:entries,error}=await supabase.from("snapshot_entries").select("*").eq("snapshot_id",s.id).order("path");if(error){setError(error.message);setBusy(false);return}const del=await supabase.from("project_nodes").delete().eq("project_id",id);if(del.error){setError(del.error.message);setBusy(false);return}const pathToId=new Map<string,string>();for(const e of (entries??[]) as any[]){const parts=e.path.split("/");let parentId:string|null=null;let built="";for(const name of parts){built=built?`${built}/${name}`:name;const cached=pathToId.get(built);if(cached){parentId=cached;continue}const{data:created,error:ce}=await supabase.from("project_nodes").insert({project_id:id,parent_id:parentId,name,type:built===e.path?e.type:"folder",path:built,mime_type:built===e.path?e.mime_type:null,size_bytes:built===e.path?e.size_bytes:0,content_hash:built===e.path?e.content_hash:null,storage_key:built===e.path?e.storage_key:null,is_sensitive:built===e.path?e.is_sensitive:false}).select("id").single();if(ce||!created){setError(ce?.message||"Could not restore filesystem");setBusy(false);return}pathToId.set(built,created.id);parentId=created.id}}await createSnapshot(`Restored from v${s.version}`,"restore");setBusy(false)}
 async function compareSnapshots(left:Snap,right:Snap){const[a,b]=await Promise.all([supabase.from("snapshot_entries").select("path,type,content_hash,size_bytes").eq("snapshot_id",left.id),supabase.from("snapshot_entries").select("path,type,content_hash,size_bytes").eq("snapshot_id",right.id)]);if(a.error||b.error){setError(a.error?.message||b.error?.message||"Could not compare snapshots");return}const am=new Map((a.data??[]).map((e:any)=>[e.path,e]));const bm=new Map((b.data??[]).map((e:any)=>[e.path,e]));setDiff({added:[...bm.keys()].filter(p=>!am.has(p)),removed:[...am.keys()].filter(p=>!bm.has(p)),changed:[...bm.keys()].filter(p=>am.has(p)&&(am.get(p).content_hash!==bm.get(p).content_hash||am.get(p).type!==bm.get(p).type||am.get(p).size_bytes!==bm.get(p).size_bytes))});setCompare({left,right})}
 return <main className="min-h-screen bg-[#080b0a] text-[#f4f3ee]"><div className="mx-auto max-w-5xl px-6 py-10 lg:px-10"><Link to="/projects/$id" params={{id}} className="inline-flex items-center gap-2 text-sm text-white/35 hover:text-white"><ArrowLeft className="h-4 w-4"/> Project</Link><div className="mt-10 flex items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-[#d7e5b0]/60">Project history</p><h1 className="mt-2 text-4xl tracking-[-.04em]">Snapshots</h1><p className="mt-2 text-sm text-white/40">Immutable states. Restores create a new recorded state rather than erasing history.</p></div><button disabled={busy} onClick={()=>void createSnapshot()} className="inline-flex items-center gap-2 rounded-xl bg-[#d7e5b0] px-4 py-3 text-sm font-semibold text-[#10150f]"><Plus className="h-4 w-4"/> Create snapshot</button></div>{error&&<p className="mt-6 rounded-xl border border-red-400/20 bg-red-400/5 px-4 py-3 text-sm text-red-200">{error}</p>}<div className="mt-10 space-y-3">{snaps.length===0?<div className="rounded-3xl border border-dashed border-white/10 p-14 text-center text-sm text-white/30">No snapshots yet.</div>:snaps.map(s=><article key={s.id} className="flex flex-col gap-5 rounded-2xl border border-white/8 bg-white/[.025] p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-3"><span className="rounded-full bg-[#d7e5b0]/10 px-3 py-1 text-xs text-[#d7e5b0]">v{s.version}</span><h2>{s.label}</h2></div><p className="mt-2 text-xs text-white/30">{s.file_count} files · {s.folder_count} folders · {new Date(s.created_at).toLocaleString()}</p></div><div className="flex gap-2"><button onClick={()=>{const other=snaps.find(x=>x.id!==s.id);if(other)void compareSnapshots(s,other)}} className="inline-flex items-center gap-2 rounded-lg border border-white/8 px-3 py-2 text-xs text-white/45 hover:text-white"><GitCompareArrows className="h-3.5 w-3.5"/> Compare</button><button disabled={busy} onClick={()=>void restore(s)} className="inline-flex items-center gap-2 rounded-lg border border-white/8 px-3 py-2 text-xs text-white/55 hover:text-white"><RotateCcw className="h-3.5 w-3.5"/> Restore</button></div></article>)}</div>{compare&&<div className="mt-8 rounded-2xl border border-white/10 bg-white/[.025] p-6"><div className="flex items-center justify-between"><div><h2>v{compare.left.version} → v{compare.right.version}</h2><p className="mt-1 text-xs text-white/30">Path-level snapshot comparison</p></div><button onClick={()=>setCompare(null)}><X className="h-4 w-4 text-white/30"/></button></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Diff title="Added" items={diff.added}/><Diff title="Removed" items={diff.removed}/><Diff title="Changed" items={diff.changed}/></div></div>}</div></main>}
function Diff({title,items}:{title:string;items:string[]}){return <div className="rounded-xl border border-white/6 p-4"><div className="text-xs uppercase tracking-[.14em] text-white/30">{title} · {items.length}</div><div className="mt-3 max-h-48 overflow-auto space-y-1">{items.map(x=><div key={x} className="truncate font-mono text-[11px] text-white/55">{x}</div>)}{!items.length&&<div className="text-xs text-white/20">None</div>}</div></div>}
