import { useEffect, useState } from "react";
import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowLeft, GitCompareArrows, RotateCcw, Plus } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { requireUser } from "@/lib/auth";

export const Route = createFileRoute("/projects/$id/snapshots")({ component: SnapshotsPage });
type Snap={id:string;version:number;label:string;message:string;origin:string;file_count:number;folder_count:number;storage_bytes:number;created_at:string};
function SnapshotsPage(){const{id}=Route.useParams();const[snaps,setSnaps]=useState<Snap[]>([]);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 async function load(){await requireUser();const{data,error}=await supabase.from("snapshots").select("*").eq("project_id",id).order("version",{ascending:false});if(error)throw error;setSnaps((data??[]) as Snap[])}useEffect(()=>{load().catch(e=>setError(e.message))},[id]);
 async function createSnapshot(){setBusy(true);setError("");const user=await requireUser();const{data:project}=await supabase.from("projects").select("current_version").eq("id",id).single();const{data:nodes,error:ne}=await supabase.from("project_nodes").select("*").eq("project_id",id);if(ne){setError(ne.message);setBusy(false);return}const version=(project?.current_version??0)+1;const{data:snap,error}=await supabase.from("snapshots").insert({project_id:id,created_by:user.id,version,label:`Version ${version}`,message:"Manual snapshot",origin:"manual",file_count:(nodes??[]).filter(n=>n.type==="file").length,folder_count:(nodes??[]).filter(n=>n.type==="folder").length,storage_bytes:(nodes??[]).reduce((s,n)=>s+Number(n.size_bytes||0),0)}).select().single();if(error||!snap){setError(error?.message||"Could not create snapshot");setBusy(false);return}const entries=(nodes??[]).map(n=>({snapshot_id:snap.id,project_id:id,path:n.path,type:n.type,mime_type:n.mime_type,size_bytes:n.size_bytes,content_hash:n.content_hash,storage_key:n.storage_key,is_sensitive:n.is_sensitive}));if(entries.length){const{error}=await supabase.from("snapshot_entries").insert(entries);if(error)setError(error.message)}await supabase.from("projects").update({current_version:version}).eq("id",id);await load();setBusy(false)}
 async function restore(s:Snap){if(!confirm(`Restore ${s.label}? This will replace the current filesystem with the snapshot state. History remains.`))return;setBusy(true);const{data:entries,error}=await supabase.from("snapshot_entries").select("*").eq("snapshot_id",s.id).order("path");if(error){setError(error.message);setBusy(false);return}await supabase.from("project_nodes").delete().eq("project_id",id);if(entries?.length){const rows=entries.map((e:any)=>({project_id:id,parent_id:null,name:e.path.split("/").pop(),type:e.type,path:e.path,mime_type:e.mime_type,size_bytes:e.size_bytes,content_hash:e.content_hash,storage_key:e.storage_key,is_sensitive:e.is_sensitive}));const{error}=await supabase.from("project_nodes").insert(rows);if(error)setError(error.message)}const{data:p}=await supabase.from("projects").select("current_version").eq("id",id).single();const next=(p?.current_version??s.version)+1;await supabase.from("projects").update({current_version:next}).eq("id",id);setBusy(false);await load()}
 return <main className="min-h-screen bg-[#080b0a] text-[#f4f3ee]"><div className="mx-auto max-w-5xl px-6 py-10 lg:px-10"><Link to="/projects/$id" params={{id}} className="inline-flex items-center gap-2 text-sm text-white/35 hover:text-white"><ArrowLeft className="h-4 w-4"/> Project</Link><div className="mt-10 flex items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-[#d7e5b0]/60">Project history</p><h1 className="mt-2 text-4xl tracking-[-.04em]">Snapshots</h1><p className="mt-2 text-sm text-white/40">Immutable project states. Restores create a new current state rather than erasing history.</p></div><button disabled={busy} onClick={createSnapshot} className="inline-flex items-center gap-2 rounded-xl bg-[#d7e5b0] px-4 py-3 text-sm font-semibold text-[#10150f]"><Plus className="h-4 w-4"/> Create snapshot</button></div>{error&&<p className="mt-6 rounded-xl border border-red-400/20 bg-red-400/5 px-4 py-3 text-sm text-red-200">{error}</p>}<div className="mt-10 space-y-3">{snaps.length===0?<div className="rounded-3xl border border-dashed border-white/10 p-14 text-center text-sm text-white/30">No snapshots yet.</div>:snaps.map(s=><article key={s.id} className="flex flex-col gap-5 rounded-2xl border border-white/8 bg-white/[.025] p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-3"><span className="rounded-full bg-[#d7e5b0]/10 px-3 py-1 text-xs text-[#d7e5b0]">v{s.version}</span><h2>{s.label}</h2></div><p className="mt-2 text-xs text-white/30">{s.file_count} files · {s.folder_count} folders · {new Date(s.created_at).toLocaleString()}</p></div><div className="flex gap-2"><button className="inline-flex items-center gap-2 rounded-lg border border-white/8 px-3 py-2 text-xs text-white/45 hover:text-white"><GitCompareArrows className="h-3.5 w-3.5"/> Compare</button><button disabled={busy} onClick={()=>restore(s)} className="inline-flex items-center gap-2 rounded-lg border border-white/8 px-3 py-2 text-xs text-white/55 hover:text-white"><RotateCcw className="h-3.5 w-3.5"/> Restore</button></div></article>)}</div></div></main>}
