import { useEffect, useState } from "react";
import { Link, createFileRoute, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, Archive, Code2, Download, Pencil, Save, Trash2, Upload } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { requireUser } from "@/lib/auth";

export const Route = createFileRoute("/projects/$id")({ component: ProjectPage });

type Project={id:string;name:string;description:string;status:string;file_count:number;folder_count:number;storage_bytes:number;current_version:number;updated_at:string};
function ProjectPage(){const{ id }=Route.useParams();const navigate=useNavigate();const[p,setP]=useState<Project|null>(null);const[error,setError]=useState("");const[name,setName]=useState("");const[desc,setDesc]=useState("");const[editing,setEditing]=useState(false);const[busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{try{const user=await requireUser();const{data,error}=await supabase.from("projects").select("*").eq("id",id).eq("owner_id",user.id).single();if(error)throw error;setP(data as Project);setName(data.name);setDesc(data.description)}catch(e){setError(e instanceof Error?e.message:"Project unavailable")}})()},[id]);
 async function save(){if(!p)return;setBusy(true);const{data,error}=await supabase.from("projects").update({name:name.trim(),description:desc.trim()}).eq("id",p.id).select().single();if(error)setError(error.message);else{setP(data as Project);setEditing(false)}setBusy(false)}
 async function remove(){if(!confirm("Delete this project permanently?"))return;await supabase.from("projects").delete().eq("id",id);await navigate({to:"/dashboard"})}
 async function archive(){await supabase.from("projects").update({status:"archived"}).eq("id",id);setP(p?{...p,status:"archived"}:p)}
 if(error&&!p)return <main className="min-h-screen bg-[#080b0a] p-10 text-white"><p className="text-red-200">{error}</p><Link to="/dashboard" className="mt-5 inline-block text-[#d7e5b0]">Back to dashboard</Link></main>;
 return <main className="min-h-screen bg-[#080b0a] text-[#f4f3ee]"><div className="mx-auto max-w-7xl px-6 py-8 lg:px-10"><Link to="/dashboard" className="inline-flex items-center gap-2 text-sm text-white/35 hover:text-white"><ArrowLeft className="h-4 w-4"/> Projects</Link>{p&&<><div className="mt-10 flex flex-col justify-between gap-5 md:flex-row md:items-start"><div className="min-w-0 flex-1">{editing?<div className="space-y-3"><input value={name} onChange={e=>setName(e.target.value)} className="w-full max-w-2xl rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-3xl outline-none"/><textarea value={desc} onChange={e=>setDesc(e.target.value)} className="w-full max-w-2xl rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm outline-none" rows={3}/></div>:<><h1 className="truncate text-4xl tracking-[-.04em]">{p.name}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/40">{p.description||"No description"}</p></>}</div><div className="flex flex-wrap gap-2">{editing?<button disabled={busy} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-[#d7e5b0] px-4 py-2.5 text-sm font-semibold text-[#10150f]"><Save className="h-4 w-4"/> Save</button>:<button onClick={()=>setEditing(true)} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm text-white/70"><Pencil className="h-4 w-4"/> Edit</button>}<button onClick={()=>archive()} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm text-white/50"><Archive className="h-4 w-4"/> Archive</button><button onClick={remove} className="inline-flex items-center gap-2 rounded-xl border border-red-300/10 px-4 py-2.5 text-sm text-red-200/60"><Trash2 className="h-4 w-4"/> Delete</button></div></div>
 <div className="mt-12 grid gap-4 sm:grid-cols-3"><Stat label="Files" value={p.file_count}/><Stat label="Folders" value={p.folder_count}/><Stat label="Current version" value={`v${p.current_version}`}/></div>
 <div className="mt-8 grid gap-4 md:grid-cols-3"><Link to="/projects/$id/workspace" params={{id}} className="rounded-3xl border border-white/8 bg-white/[.025] p-7 hover:border-white/15"><Code2 className="h-6 w-6 text-[#d7e5b0]"/><h2 className="mt-8 text-xl">Open workspace</h2><p className="mt-2 text-sm leading-6 text-white/35">Edit real files with the Aether code editor.</p></Link><Link to="/projects/$id/snapshots" params={{id}} className="rounded-3xl border border-white/8 bg-white/[.025] p-7 hover:border-white/15"><Archive className="h-6 w-6 text-[#d7e5b0]"/><h2 className="mt-8 text-xl">Snapshots</h2><p className="mt-2 text-sm leading-6 text-white/35">Create and restore immutable project states.</p></Link><div className="rounded-3xl border border-white/8 bg-white/[.025] p-7"><Upload className="h-6 w-6 text-[#d7e5b0]"/><h2 className="mt-8 text-xl">Import / export</h2><p className="mt-2 text-sm leading-6 text-white/35">Archive support is available from the workspace.</p></div></div></>}</div></main>}
function Stat({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-5"><div className="text-xs uppercase tracking-[.16em] text-white/25">{label}</div><div className="mt-3 text-2xl">{value}</div></div>}
