// This file is automatically generated. Do not edit it directly.
// Server-only Supabase client with an elevated secret key. Never import this
// module into browser code or expose its key to users.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  const url = process.env['SUPABASE_URL'];
  const secretKey = process.env['SUPABASE_SECRET_KEY'] || process.env['SUPABASE_SERVICE_ROLE_KEY'];

  if (!url || !secretKey) {
    const missing = [
      ...(!url ? ['SUPABASE_URL'] : []),
      ...(!secretKey ? ['SUPABASE_SECRET_KEY'] : []),
    ];
    throw new Error(`Missing Supabase server configuration: ${missing.join(', ')}.`);
  }

  return createClient<Database>(url, secretKey, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
